package com.pedilo.app.core.model

data class AdminOrderSummary(
    val id: String,
    val trackingNumber: String,
    val publicOrderNumber: String,
    val status: String,
    val publicStatus: String,
    val operationalStatus: String,
    val responsibleRole: String,
    val priority: String,
    val needsAttention: Boolean,
    val activeIncident: Boolean,
    val nextAllowedActions: List<LiveOrderAction>,
    val source: String,
    val requestType: String,
    val storeName: String,
    val createdAtMillis: Long?,
    val total: String,
    val paymentMethod: String = "",
    val amountToCollect: String = "",
    val collectedAmount: String = "",
    val collectionRequired: Boolean = false,
    val cashResponsibleRole: String = "",
    val orderType: String = "",
    val financialStatus: String = "",
    val communicationStatus: String = "",
    val aiRiskLevel: String = "",
    val aiClassification: String = "",
    val aiSuggestedAction: String = "",
    val aiRequiresHumanReview: Boolean = false,
    val incidentStatus: String = "",
    val archiveStatus: String = "",
    val currentResponsibleRole: String = "",
    val assignedActorId: String = "",
    val assignedActorRole: String = "",
    val version: Int = 0,
    val idempotencyKey: String = "",
)

data class AdminOrderDetail(
    val id: String,
    val trackingNumber: String,
    val publicOrderNumber: String,
    val status: String,
    val publicStatus: String,
    val operationalStatus: String,
    val responsibleRole: String,
    val priority: String,
    val needsAttention: Boolean,
    val activeIncident: Boolean,
    val nextAllowedActions: List<LiveOrderAction>,
    val source: String,
    val requestType: String,
    val storeName: String,
    val customerName: String,
    val customerPhone: String = "",
    val customerAddress: String = "",
    val createdAtMillis: Long?,
    val updatedAtMillis: Long?,
    val total: String,
    val paymentMethod: String = "",
    val amountToCollect: String = "",
    val collectedAmount: String = "",
    val collectionRequired: Boolean = false,
    val cashResponsibleRole: String = "",
    val financialNotes: String = "",
    val itemsSummary: List<String>,
    val lastEventSummary: String,
    val orderType: String = "",
    val financialStatus: String = "",
    val communicationStatus: String = "",
    val aiRiskLevel: String = "",
    val aiClassification: String = "",
    val aiSuggestedAction: String = "",
    val aiRequiresHumanReview: Boolean = false,
    val incidentStatus: String = "",
    val archiveStatus: String = "",
    val currentResponsibleRole: String = "",
    val assignedActorId: String = "",
    val assignedActorRole: String = "",
    val version: Int = 0,
    val idempotencyKey: String = "",
    val events: List<AdminOrderEvent> = emptyList(),
)

data class AdminOperationalHealthReport(
    val healthStatus: String = "unknown",
    val severity: String = "unknown",
    val generatedAt: String = "",
    val metrics: AdminOperationalHealthMetrics = AdminOperationalHealthMetrics(),
    val modules: List<AdminModuleHealth> = emptyList(),
    val alerts: List<AdminHealthAlert> = emptyList(),
    val criticalEvents: List<AdminCriticalEvent> = emptyList(),
    val auditSummary: AdminAuditSummary = AdminAuditSummary(),
    val securitySignals: List<AdminHealthAlert> = emptyList(),
)

data class AdminOperationalHealthMetrics(
    val liveOrders: Int = 0,
    val pendingReviewOrders: Int = 0,
    val openIncidentOrders: Int = 0,
    val cancelledOrders: Int = 0,
    val closedOrders: Int = 0,
    val failedCommunicationOrders: Int = 0,
    val preparedCommunicationOrders: Int = 0,
    val disabledCommunicationOrders: Int = 0,
    val financialReviewOrders: Int = 0,
    val pendingAiSuggestionOrders: Int = 0,
    val publicClaimsReceived: Int = 0,
    val linkedPublicClaims: Int = 0,
    val unlinkedPublicClaims: Int = 0,
    val requiresAttention: Int = 0,
    val collectOnDeliveryOrders: Int = 0,
    val transferDeclaredPending: Int = 0,
    val paidDeclaredUnconfirmed: Int = 0,
    val collectionPendingOrders: Int = 0,
    val openIncidents: Int = 0,
    val resolvedIncidents: Int = 0,
    val unresolvedIncidents: Int = 0,
    val aiSuggested: Int = 0,
    val aiAccepted: Int = 0,
    val aiRejected: Int = 0,
    val aiNotApplicable: Int = 0,
    val highRiskAi: Int = 0,
    val whatsappDisabled: Boolean = true,
    val pushDisabled: Boolean = true,
    val externalAiDisabled: Boolean = true,
    val engineVersion: String = "",
    val providerStatus: String = "disabled",
)

data class AdminModuleHealth(
    val key: String,
    val label: String,
    val moduleStatus: String,
    val healthStatus: String,
    val severity: String,
    val warningCode: String,
    val warningMessage: String,
)

data class AdminHealthAlert(
    val healthStatus: String,
    val severity: String,
    val scope: String,
    val source: String,
    val metricKey: String,
    val metricValue: String,
    val warningCode: String,
    val warningMessage: String,
    val requiresAdminReview: Boolean,
    val relatedOrderId: String = "",
)

data class AdminCriticalEvent(
    val relatedOrderId: String,
    val source: String,
    val type: String,
    val summary: String,
    val actorRole: String,
    val previousStatus: String,
    val nextStatus: String,
    val severity: String,
)

data class AdminAuditSummary(
    val ordersWithEvents: Int = 0,
    val orderEventRecords: Int = 0,
    val incidentRecords: Int = 0,
    val claimRecords: Int = 0,
    val communicationRecords: Int = 0,
    val aiDecisionRecords: Int = 0,
    val publicClaimRecords: Int = 0,
    val exposesPublicAudit: Boolean = false,
    val correctiveActionsExecuted: Boolean = false,
)

data class AdminTeamUser(
    val uid: String,
    val email: String,
    val displayName: String,
    val role: String,
    val active: Boolean,
    val storeId: String = "",
    val driverId: String = "",
    val updatedAtMillis: Long? = null,
)

data class AdminConfigState(
    val id: String = "real_use",
    val rainMode: Boolean = false,
    val rainDeliveryFee: Int = 4000,
    val baseDeliveryFee: Int = 3500,
    val distanceSurcharge: Int = 1500,
    val lastUpdatedBy: String = "",
    val updatedAtMillis: Long? = null,
)

data class AdminConfigUpdateRequest(
    val field: String,
    val enabled: Boolean? = null,
    val amount: Int? = null,
)

data class AdminRoleUpdateRequest(
    val uid: String,
    val role: String? = null,
    val active: Boolean? = null,
)

data class AdminMutationResult(
    val message: String,
)
